[package]
name = "crochee_plugin"
license = "MIT"
version = "0.1.0"
authors = ["crochee <2843065113@qq.com>"]
edition = "2018"
description = "a simple plugin for system"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
